# Generated by Django 4.0 on 2022-01-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_shopuserprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='aboutMe',
            new_name='about_me',
        ),
    ]
