# Generated by Django 4.0 on 2022-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='info_items',
            field=models.TextField(blank=True, verbose_name='Общие параметры'),
        ),
    ]
